version: '3.8'

services:
    app:
        image: laravelphp/php-fpm
        container_name: laravel-app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - laravel

    brand_manager_webserver:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    brand_manager_db:
        image: mariadb:11.4
        container_name: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
#        volumes:
#            - db_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    db_data:
